version: '3.8'

services:
  ssh-proxy:
    build:
      context: .
      dockerfile: docker/websockets/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SSH_PROXY_PORT=8080
    restart: unless-stopped
    networks:
      - pingtone-network

networks:
  pingtone-network:
    driver: bridge
